### ISSUE TITLE
hpcups / hpijs bug

### ISSUE THREAD

**Issue by Jason5679** [elementary/switchboard-plug-printers#101]
I have a HP-printer which worked perfectly under Ubuntu 18.04. Since I switched to Elementary OS Juno my printer (HP-Officejet-4630) doesn't work anymore. After a few tests, I noticed that if i switch between the hpcups and the hpijs driver the printer work for few minutes.

Elementary gives me: (cups-missing-filter-warning)
Libre Office ( Rejecting jobs )

**Comment by tuxiano** [comment]
Hi, I added my hp printer via hp-setup:

https://help.ubuntu.com/community/HpAllInOne

**Comment by Jason5679** [comment]
It works with the browser configuration. ( http://localhost:631 )
