### ISSUE TITLE
Epson wf3640 doesn't print on wifi

### ISSUE THREAD

**Issue by watzy2** [elementary/switchboard-plug-printers#103]
With a Dell vostro 5370 and an Epson wf3640 connected in wifi in the same network, printer is found in system settings and i can see the printer setup panel, but doesn't print any content, test page included.

I tried to remove it and install it again but this didn't solve the issue.

**Comment by peteruithoven** [comment]
Thanks for the report! Could this be a duplicate of #97?

**Comment by lenemter** [comment]
Closing because not further information provided.
