### ISSUE TITLE
printer does not disappear

### ISSUE THREAD

**Issue by S0llarCode** [elementary/switchboard-plug-printers#106]
Hi!
When i click on suppr button and valid, the printer does not disappear.

> s0llar@msi-GE60-2OE:~$ gdb io.elementary.switchboard 
> GNU gdb (Ubuntu 8.1-0ubuntu3) 8.1.0.20180409-git
> Copyright (C) 2018 Free Software Foundation, Inc.
> License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
> This is free software: you are free to change and redistribute it.
> There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
> and "show warranty" for details.
> This GDB was configured as "x86_64-linux-gnu".
> Type "show configuration" for configuration details.
> For bug reporting instructions, please see:
> <http://www.gnu.org/software/gdb/bugs/>.
> Find the GDB manual and other documentation resources online at:
> <http://www.gnu.org/software/gdb/documentation/>.
> For help, type "help".
> Type "apropos word" to search for commands related to "word"...
> Reading symbols from io.elementary.switchboard...(no debugging symbols found)...done.
> (gdb) run
> Starting program: /usr/bin/io.elementary.switchboard 
> [Thread debugging using libthread_db enabled]
> Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
> [New Thread 0x7fffe4e67700 (LWP 6588)]
> [New Thread 0x7fffdffff700 (LWP 6589)]
> [New Thread 0x7fffd421d700 (LWP 6590)]
> [New Thread 0x7fffc166b700 (LWP 6591)]
> 
> ** (io.elementary.switchboard:6584): CRITICAL **: 11:10:10.381: Printer.vala:349: Error: client-error-not-found
> 
> ** (io.elementary.switchboard:6584): CRITICAL **: 11:10:10.381: Printer.vala:380: Error: client-error-not-found
> 
> ** (io.elementary.switchboard:6584): CRITICAL **: 11:10:10.381: Printer.vala:414: Error: client-error-not-found
> 
> ** (io.elementary.switchboard:6584): CRITICAL **: 11:10:10.382: Printer.vala:528: Error: client-error-not-found
> 
> ** (io.elementary.switchboard:6584): CRITICAL **: 11:10:10.382: Printer.vala:476: Error: client-error-not-found
> 
> ** (io.elementary.switchboard:6584): CRITICAL **: 11:10:10.382: Printer.vala:445: Error: client-error-not-found
> 
> ** (io.elementary.switchboard:6584): CRITICAL **: 11:10:10.382: Printer.vala:572: Error: client-error-not-found
> 
> ** (io.elementary.switchboard:6584): CRITICAL **: 11:10:10.382: Printer.vala:507: Error: client-error-not-found
> 
> ** (io.elementary.switchboard:6584): CRITICAL **: 11:10:10.382: Printer.vala:588: Error: client-error-not-found
> 
> ** (io.elementary.switchboard:6584): CRITICAL **: 11:10:10.383: Printer.vala:660: Error: client-error-not-found
> [Thread 0x7fffc166b700 (LWP 6591) exited]
> [Thread 0x7fffd421d700 (LWP 6590) exited]
> [Thread 0x7fffdffff700 (LWP 6589) exited]
> [Thread 0x7ffff7faaac0 (LWP 6584) exited]
> [Inferior 1 (process 6584) exited normally]
> (gdb) bt
> No stack.
> (gdb)

**Comment by peteruithoven** [comment]
"suppr button"?
"valid"?
I'm closing this one it doesn't make any sense.
