### ISSUE TITLE
Unable to add a network printer (Brother MFC9450CDN)

### ISSUE THREAD

**Issue by chipmunk03** [elementary/switchboard-plug-printers#110]
In the previous version of e-os (0.4) it was a peace of cake to add to printer, but in this new version I've spent hours to get the job done and failed. What happend to the new way of configuring printers? It used to be so simple.

**Comment by peteruithoven** [comment]
Basically the only information you've included is "I've spent hours to get the job done and failed"? Please clarify what fails and how. 
I think we used a settings page we inherited from gnome, we now switched to our own thing.
