### ISSUE TITLE
Won't compile

### ISSUE THREAD

**Issue by Enerccio** [elementary/switchboard-plug-printers#117]
https://github.com/elementary/switchboard-plug-printers/blame/master/vapi/cups.vapi#L606 

    /_slow/tmp-pakku/switchboard-plug-printers-git/src/switchboard-plug-printers/vapi/cups.vapi:610.6-610.31: error: use of possibly unassigned local variable `char_values`

**Comment by Enerccio** [comment]
I fixed it for my build with `= {};`

**Comment by tintou** [comment]
Would you mind opening a PR?

**Comment by Enerccio** [comment]
Done: #118
