### ISSUE TITLE
GCC 9 build failure

### ISSUE THREAD

**Issue by alucryd** [elementary/switchboard-plug-printers#126]
Hi guys, the latest release (2.1.7) fails to build on Arch Linux with GCC 9.2.0.

Please find the relevant log here: https://buildbot.alucryd.xyz/#/builders/145/builds/1/steps/7/logs/stdio

**Comment by tintou** [comment]
It looks like the build log isn't available anymore

**Comment by alucryd** [comment]
Looks like this is no longer valid, it builds fine now :)
