### ISSUE TITLE
Use newer list add/remove pattern

### ISSUE THREAD

**Issue by cassidyjames** [elementary/switchboard-plug-printers#138]
Someone on the community Slack mentioned that adding and removing printers could be improved. I think our newer list pattern like in the Wallet plug would work better here.

**Comment by internetman420** [comment]
Will this be adressed in 6.0? It's actually quite intuitively hard to randomly lay your eyes on those +/- buttons.

![Screenshot from 2021-02-09 01 27 17](https://user-images.githubusercontent.com/63474498/107298766-43bbd300-6a76-11eb-93cd-2862d5991ac3.png)
