### ISSUE TITLE
Inconsistent vertical spacing of buttons

### ISSUE THREAD

**Issue by andrewdbate** [elementary/switchboard-plug-printers#155]
### What Happened?

The vertical spacing of buttons in the add printer dialog looks inconsistent with the Printers settings plug. See the annotated screenshot:
![printers_inconsistent-vertical_spacing](https://user-images.githubusercontent.com/2998569/154993074-b754ad9f-0465-4af5-a304-5aa7fb1e1576.png)

This is probably a question of design, but it just doesn't look quite right to me.

Thanks!

### Steps to Reproduce

1. Go to Settings, then open Printers.
2. Click the + in the bottom left corner.
3. The vertical placement of buttons in the dialog that opens is inconsistent to the vertical placement of buttons in the Printers plug within Settings.

### Expected Behavior

The distance between the bottom of the buttons and the edge of the dialog should be the same in both windows (i.e., both the Printers plug and the dialog that shows after clicking +).

### OS Version

6.x (Odin)

### Software Version

Latest release (I have run all updates)

**Comment by danirabbit** [comment]
Fixed in #191
