### ISSUE TITLE
Fix: Application doesn't allow you to cancel a file that is in the print queue.

### ISSUE THREAD

**Issue by btd1337** [elementary/switchboard-plug-printers#24]
Application doesn't allow you to cancel a file that is in the print queue.

![Print Queue](https://user-images.githubusercontent.com/11943860/28632146-ef092054-7205-11e7-8b29-4fc7d0d71d6a.png)

And the system constantly tries to print.

![Attempted Printing](https://user-images.githubusercontent.com/11943860/28632227-36af0f2c-7206-11e7-9d2b-89d9adf356e2.png)

**Comment by Thalexander** [comment]
I think there is a permissions issue with cups_pk_helper (so I guess that would be pokit) as the calls don't show up in the cups log despite cups_pk_helper returning "sucessful-ok". Running the plug under root the buttons work correctly (with regard to the backend, they show no visual feedback anything has happened until you restart switchboard, or they are removed from the list_store and re-added such as toggling completed jobs twice for cancelled jobs) and the actions appear in the cups log.

**Comment by tuxiano** [comment]
Issue still persist. I have to open localhost:631 to delete a sucked print job.

**Comment by danrabbit** [comment]
This was resolved somewhere along the way. It's now possible to cancel print jobs
