### ISSUE TITLE
Switchboard crashes when attempting to access printers plug

### ISSUE THREAD

**Issue by cmonagle** [elementary/switchboard-plug-printers#33]
following is output when called from terminal:
```
[INFO 14:32:10.711858] Application.vala:153: System Settings version: 2.0
[INFO 14:32:10.711886] Application.vala:155: Kernel version: 4.4.0-97-generic
[WARNING 14:32:10.713276] Switchboard.vala:120: Calling Switchboard directly is deprecated, please use the settings:// scheme instead
**
ERROR:arraylist.c:967:gee_array_list_real_get: assertion failed: (index < _size)
Aborted (core dumped)
```

Edit: This [SO question](https://elementaryos.stackexchange.com/questions/13414/printer-section-crashes-system-settings) seems to be the same issue.

**Comment by Thalexander** [comment]
Most likely from the populate_values function in InkLevel as that is the only place where an ArrayList has elements directly accessed by indexes.
