### ISSUE TITLE
Display job status in line

### ISSUE THREAD

**Issue by danrabbit** [elementary/switchboard-plug-printers#72]
Instead of in a tooltip, it would be nice to display job status inline

**Comment by jeremypw** [comment]
@danrabbit  There is also an icon that reflects the state to the extent of "paused" (when held or stopped), "error" (when cancelled or aborted) or "completed". There is no icon for "pending" or "processing" states however so I guess a label would be more precise.   Completed jobs appear under a "Completed" header though so a label is rather redundant for these.
