### ISSUE TITLE
Switch status does not change status in printer list.

### ISSUE THREAD

**Issue by jeremypw** [elementary/switchboard-plug-printers#90]
Toggling the switch in the printer page does not change the appearance and message for the printer in the printer list.  NB The printer in question is attached to a local server and the issue occurs on a client.  Printing to the printer from e.g. Chromium on the client was successful.

**Comment by torikulhabib** [comment]
![gifout](https://user-images.githubusercontent.com/26135527/43685971-1107935c-98e8-11e8-88ed-a634da3e071e.gif)

**Comment by gre0j** [comment]
#123
