### ISSUE TITLE
More clearly differentiate blacks

### ISSUE THREAD

**Issue by cassidyjames** [elementary/switchboard-plug-printers#91]
Our color printer has a "pigment black" in addition to a black ink—the pigment is used for pure black text, while the other is used to mix with other colors to create darker shades.

![screenshot](https://user-images.githubusercontent.com/611168/44412521-619fc100-a526-11e8-8662-bc7c9d93eb82.png)

It looks like we're using _ever_ so slightly different shades for the two blacks now, but it would be handy to further differentiate them at a glance. The non-pigment black could probably be lightened a little more (it will still look black next to the CMYK colors), while the pigment black should remain pure black.

**Comment by lainsce** [comment]
I suggest using #444444 for the non-pigment black. :smile:

**Comment by tintou** [comment]
The issue is that the color comes from the driver of your printer so the only solution here is to fix #92 I'm affraid

**Comment by lainsce** [comment]
I saw in-code that it's tied to #333333 currently, unless I'm mistaken.

**Comment by tintou** [comment]
@lainsce I can't find anything about this
