### ISSUE TITLE
Label ink levels

### ISSUE THREAD

**Issue by cassidyjames** [elementary/switchboard-plug-printers#92]
Right now there's no way to tell which color is which in the ink levels without the colors themselves. This may be problematic for color blind users, when the levels are very low, or when their printers include multiple similar shades (like these two blacks):

![screenshot](https://user-images.githubusercontent.com/611168/44412521-619fc100-a526-11e8-8662-bc7c9d93eb82.png)

We should add labels below the ink levels to clearly distinguish them in another way.

**Comment by lainsce** [comment]
I tried my hand in a mockup to show a possible way around fixing this:
A label to show what these gauges are for, as well as the International Standard symbols for each color: CMYK and B.

![print-plug-ink-levels-mockup](https://user-images.githubusercontent.com/4886639/44442504-f64b0300-a5a8-11e8-864d-29ec0611a480.png)

**Comment by tintou** [comment]
Right now the color name is already available as a tooltip

**Comment by cassidyjames** [comment]
@tintou tooltips aren't really all that discoverable, clearly since I never knew they were there :sweat_smile: I think moving to an always-exposed label would be fine. It's not like we're short on space here.
