### ISSUE TITLE
Default printer dialog says "Rejecting jobs" but printer available in LibreOffice print dialog

### ISSUE THREAD

**Issue by wout** [elementary/switchboard-plug-printers#97]
My printer is randomly available and unavailable (Rejecting jobs) in the default print dialog:

![printer-rejecting-jobs](https://user-images.githubusercontent.com/107324/47296643-35cab580-d613-11e8-9040-bae731194295.png)

While at the same time, LibreOffice always shows the printer available and it's always possible to print:

![printer-operational-libreoffice](https://user-images.githubusercontent.com/107324/47296672-4e3ad000-d613-11e8-84b9-e67eecc750f9.png)

I can't find any pattern in the availability. I'm coming from Pop!_OS 18.04 where I never had any issues.

**Comment by angarod** [comment]
Same issue here on a fresh install, with a CANON MG5600 printer.

**Comment by dolphinoracle** [comment]
some observations:  the simply launching the printer plugin appears to "pause" all printers, whether in use or not.  and whether you make any changes to the printers or not.

also, sometimes there is an extra switch for "reject" and/or "accept" jobs, which I think the printers plugin turns off (possible along with the pause function) but does not reliable turn back to "accept" when printers are unpaused.

a workaround is to use the http://localhost:631 cups built-in configuration tool to manage the printers.  the reject/accept switches are present (at least for my printer) as well as the pause/resume switches.

**Comment by angarod** [comment]
I currently use this workaround, but it is not user friendly for my parents. Is it considered as a bug ?

**Comment by wout** [comment]
It's definitely a bug. In the meantime I learend that I should stay away form the printer settings altogether. As soon as I open the switchboard's printer settings, they stop working.
